""" 
TrendPulse - Task 2: Clean Data and Save as CSV This script: 

1. Loads the JSON file generated in Task 1. 
2. Removes duplicate stories. 
3. Removes rows with missing required values. 
4. Converts score and num_comments to integers. 
5. Removes low-quality stories with score < 5. 
6. Removes extra whitespace from titles. 
7. Saves the cleaned data as a CSV file. 
8. Prints a summary of stories by category. 
"""

import pandas as pd
import glob
import os

# Configuration

DATA_FOLDER = "data" 
OUTPUT_FILE = "data/trends_clean.csv"

# Step 1: Find the Task 1 JSON file

# Search for JSON files generated by Task 1.
json_files = glob.glob( 
    os.path.join(DATA_FOLDER, "trends_*.json") 
)

# Remove the cleaned CSV from consideration if necessary. 
json_files = [ 
    file for file in json_files 
    if not file.endswith("trends_clean.json") 
]

if not json_files: 
    print("Error: No Task 1 JSON file found in the data folder.") 
    print("Please run task1_data_collection.py first.") 
    exit()


# Use the most recently modified JSON file. 
input_file = max( 
    json_files, 
    key=os.path.getmtime 
)


# Step 2: Load JSON into Pandas DataFrame

try: 

    df = pd.read_json(input_file) 

except Exception as error: 

    print(f"Error loading JSON file: {error}") 
    exit() 

print(f"\nLoaded {len(df)} stories from {input_file}")



# Step 3: Remove duplicate stories

df = df.drop_duplicates( 
    subset=["post_id"] 
) 

print( f"After removing duplicates: {len(df)}" )



# Step 4: Remove rows with missing required values

# Required fields: 
# post_id 
# title 
# score

df = df.dropna( 
    subset=[ 
        "post_id", 
        "title", 
        "score" 
    ] 
)   

print( f"After removing nulls: {len(df)}" )




# Step 5: Clean whitespace from title 


df["title"] = ( 
    df["title"] 
    .astype(str) 
    .str.strip() 
)


# Step 6: Convert numeric columns to integers

# Convert score to numeric.
df["score"] = pd.to_numeric( 
    df["score"], 
    errors="coerce" 
)

# Convert num_comments to numeric. 
df["num_comments"] = pd.to_numeric( 
    df["num_comments"], 
    errors="coerce" 
)

# Remove rows where numeric conversion failed. 
df = df.dropna( 
    subset=[ 
        "score", 
        "num_comments" 
    ] 
)

# Convert numeric values to integers. 
df["score"] = df["score"].astype(int) 
df["num_comments"] = df["num_comments"].astype(int)



# Step 7: Remove low-quality stories

# Keep only stories with score >= 5.
df = df[df["score"] >= 5] 

print( f"After removing low scores: {len(df)}" )




# Step 8: Save cleaned data as CSV

try: 

    df.to_csv( 
        OUTPUT_FILE, 
        index=False, 
        encoding="utf-8" 
    )

except Exception as error: 

    print(f"Error saving CSV file: {error}") 
    exit() 

print( f"\nSaved {len(df)} rows to {OUTPUT_FILE}" )




# Step 9: Print stories per category

print("\nStories per category:") 

category_summary = ( 
    df["category"] 
    .value_counts() 
)


for category, count in category_summary.items():    

    print( 
        f" {category:<15} {count}" 
    )


# Final information


print("\nTask 2 completed successfully!")

